import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReactQueryProvider } from '@/lib/provider/ReactQueryProvider';
import { Toaster } from 'sonner';
import DesktopOnlyCursor from '@/components/DesktopOnlyCursor';
import { ServicesProvider } from '@/features/manager/components/ServicesContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-slate-900 dark:bg-black dark:text-slate-50`}
      >
        <ReactQueryProvider>
          <ServicesProvider>
            <DesktopOnlyCursor />
            {children}
            <Toaster richColors position="top-right" />
          </ServicesProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
